### ISSUE TITLE
Error while processing state change for a FirstBus sensor

### ISSUE THREAD

**Issue by swampylee** [BottlecapDave/HomeAssistant-FirstBus#10]
**Describe the bug**

**I'm seeing the following in my HA logs repeated regularly. Nothing has changed on my configuration. HA version is 2023.5.4
The actual sensors still appear to be giving the correct information.**

```
2023-06-12 14:22:22.786 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.first_bus_119_towards_hayes_next_bus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: '2023-06-12 14:33:00+01:00'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 287, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 348, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.ww_to_hayes_due has device class None, state class None unit m and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: 2023-06-12 14:33:00+01:00 ()**
```

**To Reproduce**

I assume any sensor created for bus information will produce this error.

**Expected behavior**

**Home Assistant Logs**
Are there any related logs available in Home Assistant

As posted above.

**Comment by BottlecapDave** [comment]
Out of interest, I assume you are running the latest version of the integration?

**Comment by swampylee** [comment]
Yes as far as I’m aware I am. Haven’t been told in HACS that there’s a newer version.On 12 Jun 2023, at 20:50, David Kendall ***@***.***> wrote:﻿
Out of interest, I assume you are running the latest version of the integration?

**Comment by BottlecapDave** [comment]
I'm not sure what's causing this. What's more puzzling is in the logs theres reference to a sensor `sensor.ww_to_hayes_due` which this integration doesn't create. I've added your route to my instance to see if I can recreate it locally

**Comment by swampylee** [comment]
Hi,

 

I do create these sensors based off of the attributes provided by your integration. I hope it’s not these causing the problem, and thank you for looking into this.

 

  - platform: template

    sensors:

      ww_to_croydon_due:

        friendly_name: "West Wickham to Croydon Due"

        unit_of_measurement: m

        value_template: "{{ state_attr('sensor.first_bus_119_towards_croydon_next_bus', 'Due') }}"

      ww_to_hayes_due:

        friendly_name: "West Wickham to Hayes Due"

        unit_of_measurement: m

        value_template: "{{ state_attr('sensor.first_bus_119_towards_hayes_next_bus', 'Due') }}"

      ww_to_croydon_dest:

        friendly_name: "West Wickham to Croydon Due"

        value_template: "{{ state_attr('sensor.first_bus_119_towards_croydon_next_bus', 'Destination') }}"

      ww_to_hayes_dest:

        friendly_name: "West Wickham to Hayes Due"

        value_template: "{{ state_attr('sensor.first_bus_119_towards_hayes_next_bus', 'Destination') }}"

**Comment by swampylee** [comment]
> Hi, I do create these sensors based off of the attributes provided by your integration. I hope it’s not these causing the problem, and thank you for looking into this. - platform: template sensors: ww_to_croydon_due: friendly_name: "West Wickham to Croydon Due" unit_of_measurement: m value_template: "{{ state_attr('sensor.first_bus_119_towards_croydon_next_bus', 'Due') }}" ww_to_hayes_due: friendly_name: "West Wickham to Hayes Due" unit_of_measurement: m value_template: "{{ state_attr('sensor.first_bus_119_towards_hayes_next_bus', 'Due') }}" ww_to_croydon_dest: friendly_name: "West Wickham to Croydon Due" value_template: "{{ state_attr('sensor.first_bus_119_towards_croydon_next_bus', 'Destination') }}" ww_to_hayes_dest: friendly_name: "West Wickham to Hayes Due" value_template: "{{ state_attr('sensor.first_bus_119_towards_hayes_next_bus', 'Destination') }}"

As I pasted this I noticed I'm specifying unit of measurement. I wonder if it's that - will remove and see if the error disappears. Thanks again and sorry if this was a red herring.

**Comment by BottlecapDave** [comment]
The unit of measure might be causing your issue, due is a timestamp and unit of measure looks like it's been set to minutes which would explain the invalid casting to integer.

I've been running your route on my instance and not seen any issues.

**Comment by swampylee** [comment]
> The unit of measure might be causing your issue, due is a timestamp and unit of measure looks like it's been set to minutes which would explain the invalid casting to integer.
> 
> I've been running your route on my instance and not seen any issues.

Hi Dave, yes since I removed the unit_of_measurement I haven't seen the error reappear so will close this issue. Thanks again for the prompt investigations and communication. So sorry for the false bug report, I should have spotted that sooner.

**Comment by swampylee** [comment]
Closed

**Comment by BottlecapDave** [comment]
No problem. Glad you've found the answer :)
