### ISSUE TITLE
First bus service with a space in the service number

### ISSUE THREAD

**Issue by DragonessCerridwen** [BottlecapDave/HomeAssistant-FirstBus#14]
ServiceRef  "0"
ServiceNumber  "15 B"
Destination ""
Due "52 mins"
IsFG "N"
IsLive "Y"

There is a space in the service number used by first bus on a few routes up here and it generates "Unknown" issues

Is there a way to include spaces within the ServiceNumber fields?

Many Thanks!

**Comment by BottlecapDave** [comment]
Hello. What's generating unknown issues? Setting up the integration, the value of the sensor itself? Something else? Is there any errors in your HA logs relating to the integration?

**Comment by BottlecapDave** [comment]
If you could also supply the stop, it'll help me prevent issues like this in the future

**Comment by DragonessCerridwen** [comment]
Hi There and thanks for the quick response!

What happens is our local 15 bus has had a change in its numbering lately
and they now have a "15 B" and it seems the space is throwing a spanner in
the works, after about 19:00 we end up with no notifications

https://www.firstbus.co.uk/api/get-next-bus?stop=639006463 < leaving stop
https://www.firstbus.co.uk/api/get-next-bus?stop=639007174 < destination
stop

Many Thanks!

**Comment by DragonessCerridwen** [comment]
Additionally

Cant see anything in the log in relation to first_bus

Many Thanks, sorry I missed that part out

**Comment by DragonessCerridwen** [comment]
Hi There

Tried deleting the database and it has now picked up the B route

Apologies for wasting your time

**Comment by BottlecapDave** [comment]
No problem, but not sure why deleting the database fixed your issue. I think there's an issue still there, as a) you should be able to filter buses with spaces present and b) the B route should not be picked up if you've filtered routes to the non-B route as they are different buses.

I'll try and fix these issues within the next week.

**Comment by BottlecapDave** [comment]
This should now be fixed in v1.1.4

**Comment by DragonessCerridwen** [comment]
Many thanks!
