### ISSUE TITLE
Sensor state is returning -1

### ISSUE THREAD

**Issue by CarlBird** [BottlecapDave/HomeAssistant-FirstBus#2]
The sensor state is returning -1.

I can confirm that a call via the browser returns data E.g.:

**Request:**
https://www.firstbus.co.uk/getNextBus?stop=3800C509801

**Response:**
{
   "atcocode":"3800C509801",
   "smscode":"stadtdgj",
   "request_time":"2022-08-31T13:27:03+01:00",
   "name":"Morris Square",
   "stop_name":"Morris Square",
   "bearing":"S",
   "indicator":"adj",
   "locality":"Wolstanton",
   "location":{
      "type":"Point",
      "coordinates":[
         -2.21705,
         53.03138
      ]
   },
   "departures":{
      
   },
   "source":"FirstTicketer",
   "times":[
      {
         "ServiceRef":"0",
         "ServiceNumber":"99",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"7 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"98",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"22 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"94B",
         "Destination":"Newcastle Town Centr",
         "Due":"13:56",
         "IsFG":"N",
         "IsLive":"N"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"99",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"41 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"98",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"52 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"99",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"67 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"98",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"82 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"94B",
         "Destination":"Newcastle Town Centr",
         "Due":"14:56",
         "IsFG":"N",
         "IsLive":"N"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"99",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"97 mins",
         "IsFG":"N",
         "IsLive":"Y"
      },
      {
         "ServiceRef":"0",
         "ServiceNumber":"98",
         "Destination":"NEWCASTLE, Bus Stn",
         "Due":"117 mins",
         "IsFG":"N",
         "IsLive":"Y"
      }
   ],
   "stop":{
      "code":"3800C509801",
      "mark":"1",
      "sms":"stadtdgj",
      "direction":"S",
      "latitude":"53.031400000",
      "longitude":"-2.217050000",
      "indicator":"Adj",
      "name":"stop Adj Morris Square",
      "locality":"Wolstanton",
      "qualifier":"Newcastle Under Lyme"
   },
   "fromTraveline":"31\/08\/2022 13:27"
}

**Comment by holdestmade** [comment]
Same here, API call works, HA returns -1

https://www.firstbus.co.uk/api/get-next-bus?stop=2200YEA00934

{"atcocode":"2200YEA00934","smscode":"22000934","request_time":"2022-08-31T15:34:01+01:00","name":"Hessle Boothferry Road","stop_name":"Hessle Boothferry Road","bearing":"NE","indicator":"22000934","locality":"Hessle","location":{"type":"Point","coordinates":[-0.44638,53.72914]},"departures":{},"times":[{"ServiceRef":"0","ServiceNumber":"350","Destination":"Hull Interchange","Due":"15:44","IsFG":"N","IsLive":"N"},{"ServiceRef":"0","ServiceNumber":"350|Humber FastCat","Destination":"Hull","Due":"16:15","IsFG":"N","IsLive":"N"},{"ServiceRef":"0","ServiceNumber":"55","Destination":"Hull","Due":"16:23","IsFG":"N","IsLive":"N"},{"ServiceRef":"0","ServiceNumber":"250","Destination":"Hull Hull Interchange","Due":"16:30","IsFG":"N","IsLive":"N"},{"ServiceRef":"0","ServiceNumber":"350","Destination":"Hull Interchange","Due":"16:58","IsFG":"N","IsLive":"N"},{"ServiceRef":"0","ServiceNumber":"350","Destination":"Hull Interchange","Due":"17:24","IsFG":"N","IsLive":"N"},{"ServiceRef":"0","ServiceNumber":"255","Destination":"North Point","Due":"17:29","IsFG":"N","IsLive":"N"}],"stop":{"code":"2200YEA00934","mark":"1","sms":"22000934","direction":"NE","latitude":"53.729360000","longitude":"-0.445790000","indicator":"22000934","name":"stop 22000934 Hessle Boothferry Road","locality":"Hessle","qualifier":"East Riding of Yorkshire"},"source":"(n\/a)","fromTraveline":"31\/08\/2022 15:34"}

**Comment by BottlecapDave** [comment]
Hello both. Sorry for the late reply. This seemed to be a bug when setting up a sensor but not restricting it down to a specific bus. This should now hopefully be rectified in the latest release (v1.1.0)

**Comment by holdestmade** [comment]
Hi, thanks but still the same for me on v1.1.0

**Comment by BottlecapDave** [comment]
Glad to hear :) Will close the issue now.

**Comment by holdestmade** [comment]
Just done a restart and the state takes 5 minutes to get from -1. Could you maybe add an api call on, or just after, startup to fill the state ?

**Comment by BottlecapDave** [comment]
The latest bus time should now be retrieved upon start up with the latest release (v1.1.2)

**Comment by holdestmade** [comment]
> The latest bus time should now be retrieved upon start up with the latest release (v1.1.2)

All working so far, thanks
