### ISSUE TITLE
Question: best way to display all buses on a card

### ISSUE THREAD

**Issue by aptonline** [BottlecapDave/HomeAssistant-FirstBus#47]
### Describe the feature

Sorry not a feature request but not sure how else to ask the question.  What’s the best way to display all buses for a stop on a card?

Initially, I made a value template sensor to expose the buses into another sensors state and then displaying that but I’m coming across the 255 character state limit and the sensor shows ‘unknown’ intermittently.

### Expected behaviour

Be able to take the list of buses and add them to a card.

### Use Case

As above

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-FirstBus) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. You probably want to look at the markdown card where you you can use the states_attr function to extract the buses and then iterate over and display them how you want. @garthy exposed the attribute for this purpose so might be able to share his solution (which I can put into the docs)

**Comment by aptonline** [comment]
Yeah I’m using the markdown card currently but I believe my issues is that I’m putting the list of ALL the buses in a single state which is causing the error with the limit.

Example code to see how others have done it would be useful.

thanks

**Comment by BottlecapDave** [comment]
Very basic code for your markdown card would be

```
{% set times = state_attr('sensor.first_bus_location', 'buses') %}
{% if times != None %}
{% for time in times %}
{{ time['service_number'] }} at {{ time['due'].strftime('%H:%m') }} (in {{ time_until(time['due']) }})
{% endfor %}
{% endif %}
```

where `sensor.first_bus_location` is the name of the sensor provided by this integration. You don't need to use any custom template sensors.

**Comment by aptonline** [comment]
That’s works well. The issues I was having was recreating the same in an actual sensor the. Adding that. That solution is much cleaner and works well. Many thanks. Worth adding to the docs ?

**Comment by aptonline** [comment]
Thanks again.
