### ISSUE TITLE
Support multiple providers

### ISSUE THREAD

**Issue by rtm516** [BottlecapDave/HomeAssistant-FirstBus#49]
### Describe the feature

I've used this repo to create HomeAssistant-Stagecoach but I'm no HA expert and I think it would be nice to integrate them both into the same repo with the potential to add more if people want later on.

https://github.com/rtm516/HomeAssistant-Stagecoach

Happy to assist in this if wanted.

### Expected behaviour

N/A

### Use Case

Multiple bus providers in one addon

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-FirstBus) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hi.

I'm glad you have found the integration useful and managed to create your own variation of it. Supporting other bus companies goes beyond the scope of this integration, so this is not something i'll want to proceed with.
