### ISSUE TITLE
New bus initial Minutes is 1439

### ISSUE THREAD

**Issue by holdestmade** [BottlecapDave/HomeAssistant-FirstBus#7]
**Describe the bug**
Once a bus has run down to 0, the next bus is 1439 minutes
Then, at minute intervals 1438, 1437, 1436, then correct after that

Using atcocode 2200YEA00934

Only happening on some buses, it seems to not remove the expired bus and not use the latest one

**Home Assistant Logs**
Nothing in logs about this

**Comment by swampylee** [comment]
Yes I'm seeing exactly the same and on the latest (just released) version.

**Comment by BottlecapDave** [comment]
This seems to be an intermittent issue once the bus time has passed, which should eventually correct itself.

I have done quite a bit of refactoring and added more tests which I'm currently testing. Assuming the testing goes well, this issue will hopefully be fixed within the next couple of days.

Sorry for the bug, but thanks for reporting it.

Dave

**Comment by BottlecapDave** [comment]
I'm hoping this has now been fixed in the latest release (v1.1.2). Let me know if you encounter it still

**Comment by holdestmade** [comment]
All working great so far, thanks
