### ISSUE TITLE
ActoCode Not Available on OpenStreetMap

### ISSUE THREAD

**Issue by robertwigley** [BottlecapDave/HomeAssistant-FirstBus#9]
Thanks for this integration. This not a bug, but a question about usage that is not answered in the documentation. How do you obtain the ActoCode if it is not present on OpenStreetMap? Is there an alternative method that can be used?

There are some bus stops missing on OpenStreetMap, at least in the Glasgow area and some do not have any ActoCodes assigned to them. e.g. https://www.openstreetmap.org/node/4619156282

**Comment by BottlecapDave** [comment]
Hello. 

The only other way I can think is to go to
1. Navigate to https://www.firstbus.co.uk/next-bus and type your location
2. Open up the development tools on your browser (usually F12) and go to the network tab
3. Click on the stop that your after and look at the network request. This should make a request to `https://www.firstbus.co.uk/api/get-next-bus?stop=XXX`. The value you're after will be in the response and also the value of `XXX`.

**Comment by robertwigley** [comment]
Brilliant and perfect. That worked a treat. Thank you so much. It might be worth adding this to the documentation as I'm sure there must be other stops missing on OpenStreetMap.

**Comment by BottlecapDave** [comment]
Glad this worked, and I'll update the instructions.
